site_name: Action Plan RPG
theme:
  name: material
  icon:
    logo: material/dice-d20
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: light blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
    - toc.integrate 
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
copyright: Copyright &copy; 2022 Alex Stewart
plugins:
  - search
nav:
  - Home: index.md
  - Rules:
    - Characters: rules/characters.md
    - Actions: rules/actions.md
  - The Goblin Cave:
    - Overview: the_goblin_cave/overview.md
    - The Cave: the_goblin_cave/cave.md
    - Archetypes: the_goblin_cave/archetypes.md
    - Hunger: the_goblin_cave/hunger.md
    - Inventory: the_goblin_cave/inventory.md
    - Minions: the_goblin_cave/minions.md
    - The Goblin Code: the_goblin_cave/code.md
